blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discord Community
    url: https://discord.gg/DsaXMTEtpF
    about: Ask questions and discuss ideas with the community on Discord
  - name: ðŸ“– Documentation
    url: https://docs.aliasvault.net
    about: Check out the official (self-host) documentation