# Docker Compose file for the AliasVault documentation
#
# This file is used to build the AliasVault documentation and serve it locally in development mode
# with livereload enabled.
#
# Usage:
# docker compose up -d
# docker compose down
#
services:
  jekyll:
    build:
      context: .
    volumes:
        - .:/srv/jekyll
    ports:
        - "4000:4000"
    command: bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling --livereload
    environment:
        - JEKYLL_ENV=development
        - JEKYLL_NO_CACHE=true
        - DISABLE_DISK_CACHE=true
